/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.repeatedFields_, null);
};
goog.inherits(proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.displayName = 'proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.repeatedFields_ = [3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.prototype.toObject = function(opt_includeInstance) {
  return proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.toObject = function(includeInstance, msg) {
  var f, obj = {
    authString: jspb.Message.getFieldWithDefault(msg, 1, ""),
    tableName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    columnsList: jspb.Message.getRepeatedField(msg, 3),
    clausesList: jspb.Message.getRepeatedField(msg, 4)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select;
  return proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthString(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTableName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addColumns(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addClauses(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAuthString();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTableName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getColumnsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getClausesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
};


/**
 * optional string auth_string = 1;
 * @return {string}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.prototype.getAuthString = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.prototype.setAuthString = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string table_name = 2;
 * @return {string}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.prototype.getTableName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.prototype.setTableName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string columns = 3;
 * @return {!Array<string>}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.prototype.getColumnsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/** @param {!Array<string>} value */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.prototype.setColumnsList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.prototype.addColumns = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.prototype.clearColumnsList = function() {
  this.setColumnsList([]);
};


/**
 * repeated string clauses = 4;
 * @return {!Array<string>}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.prototype.getClausesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/** @param {!Array<string>} value */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.prototype.setClausesList = function(value) {
  jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.prototype.addClauses = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Select.prototype.clearClausesList = function() {
  this.setClausesList([]);
};


