/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

goog.forwardDeclare('proto.ArmyAntMessage.DBProxy.SqlRequestType_SqlString');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString.displayName = 'proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString.prototype.toObject = function(opt_includeInstance) {
  return proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString.toObject = function(includeInstance, msg) {
  var f, obj = {
    authString: jspb.Message.getFieldWithDefault(msg, 1, ""),
    type: jspb.Message.getFieldWithDefault(msg, 2, 0),
    str: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString;
  return proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthString(value);
      break;
    case 2:
      var value = /** @type {!proto.ArmyAntMessage.DBProxy.SqlRequestType_SqlString} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setStr(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAuthString();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getStr();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string auth_string = 1;
 * @return {string}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString.prototype.getAuthString = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString.prototype.setAuthString = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional SqlRequestType_SqlString type = 2;
 * @return {!proto.ArmyAntMessage.DBProxy.SqlRequestType_SqlString}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString.prototype.getType = function() {
  return /** @type {!proto.ArmyAntMessage.DBProxy.SqlRequestType_SqlString} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.ArmyAntMessage.DBProxy.SqlRequestType_SqlString} value */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString.prototype.setType = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string str = 3;
 * @return {string}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString.prototype.getStr = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_SqlString.prototype.setStr = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


