/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.ArmyAntMessage.DBProxy.SqlTableInfo');

goog.forwardDeclare('proto.ArmyAntMessage.DBProxy.SqlRequestType');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table.displayName = 'proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table.prototype.toObject = function(opt_includeInstance) {
  return proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table.toObject = function(includeInstance, msg) {
  var f, obj = {
    authString: jspb.Message.getFieldWithDefault(msg, 1, ""),
    type: jspb.Message.getFieldWithDefault(msg, 2, 0),
    tableName: jspb.Message.getFieldWithDefault(msg, 3, ""),
    tableCreateData: (f = msg.getTableCreateData()) && proto.ArmyAntMessage.DBProxy.SqlTableInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table;
  return proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthString(value);
      break;
    case 2:
      var value = /** @type {!proto.ArmyAntMessage.DBProxy.SqlRequestType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTableName(value);
      break;
    case 4:
      var value = new proto.ArmyAntMessage.DBProxy.SqlTableInfo;
      reader.readMessage(value,proto.ArmyAntMessage.DBProxy.SqlTableInfo.deserializeBinaryFromReader);
      msg.setTableCreateData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAuthString();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getTableName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTableCreateData();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.ArmyAntMessage.DBProxy.SqlTableInfo.serializeBinaryToWriter
    );
  }
};


/**
 * optional string auth_string = 1;
 * @return {string}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table.prototype.getAuthString = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table.prototype.setAuthString = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional SqlRequestType type = 2;
 * @return {!proto.ArmyAntMessage.DBProxy.SqlRequestType}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table.prototype.getType = function() {
  return /** @type {!proto.ArmyAntMessage.DBProxy.SqlRequestType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.ArmyAntMessage.DBProxy.SqlRequestType} value */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table.prototype.setType = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional string table_name = 3;
 * @return {string}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table.prototype.getTableName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table.prototype.setTableName = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional SqlTableInfo table_create_data = 4;
 * @return {?proto.ArmyAntMessage.DBProxy.SqlTableInfo}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table.prototype.getTableCreateData = function() {
  return /** @type{?proto.ArmyAntMessage.DBProxy.SqlTableInfo} */ (
    jspb.Message.getWrapperField(this, proto.ArmyAntMessage.DBProxy.SqlTableInfo, 4));
};


/** @param {?proto.ArmyAntMessage.DBProxy.SqlTableInfo|undefined} value */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table.prototype.setTableCreateData = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table.prototype.clearTableCreateData = function() {
  this.setTableCreateData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest_Table.prototype.hasTableCreateData = function() {
  return jspb.Message.getField(this, 4) != null;
};


