# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ArmyAntMessage/System/SocketHead.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ArmyAntMessage/System/SocketHead.proto',
  package='ArmyAntMessage.System',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n&ArmyAntMessage/System/SocketHead.proto\x12\x15\x41rmyAntMessage.System\"[\n\x1bSocketExtendNormal_V0_0_0_1\x12\x0e\n\x06\x61pp_id\x18\x01 \x01(\x03\x12\x16\n\x0e\x63ontent_length\x18\x02 \x01(\x05\x12\x14\n\x0cmessage_code\x18\x03 \x01(\x05\x62\x06proto3')
)




_SOCKETEXTENDNORMAL_V0_0_0_1 = _descriptor.Descriptor(
  name='SocketExtendNormal_V0_0_0_1',
  full_name='ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='app_id', full_name='ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1.app_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content_length', full_name='ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1.content_length', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_code', full_name='ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1.message_code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=156,
)

DESCRIPTOR.message_types_by_name['SocketExtendNormal_V0_0_0_1'] = _SOCKETEXTENDNORMAL_V0_0_0_1
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SocketExtendNormal_V0_0_0_1 = _reflection.GeneratedProtocolMessageType('SocketExtendNormal_V0_0_0_1', (_message.Message,), dict(
  DESCRIPTOR = _SOCKETEXTENDNORMAL_V0_0_0_1,
  __module__ = 'ArmyAntMessage.System.SocketHead_pb2'
  # @@protoc_insertion_point(class_scope:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1)
  ))
_sym_db.RegisterMessage(SocketExtendNormal_V0_0_0_1)


# @@protoc_insertion_point(module_scope)
