// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ArmyAntMessage/System/SocketHead.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ArmyAntMessage.System {

  /// <summary>Holder for reflection information generated from ArmyAntMessage/System/SocketHead.proto</summary>
  public static partial class SocketHeadReflection {

    #region Descriptor
    /// <summary>File descriptor for ArmyAntMessage/System/SocketHead.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SocketHeadReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZBcm15QW50TWVzc2FnZS9TeXN0ZW0vU29ja2V0SGVhZC5wcm90bxIVQXJt",
            "eUFudE1lc3NhZ2UuU3lzdGVtIpcBChtTb2NrZXRFeHRlbmROb3JtYWxfVjBf",
            "MF8wXzESDgoGYXBwX2lkGAEgASgDEhYKDmNvbnRlbnRfbGVuZ3RoGAIgASgF",
            "EhQKDG1lc3NhZ2VfY29kZRgDIAEoBRIZChFjb252ZXJzYXRpb25fY29kZRgE",
            "IAEoBRIfChdjb252ZXJzYXRpb25fc3RlcF9pbmRleBgFIAEoBSp/ChRDb252",
            "ZXJzYXRpb25TdGVwVHlwZRILCgdEZWZhdWx0EAASDgoKTm90aWNlT25seRAB",
            "EgoKBkFza0ZvchACEhUKEVN0YXJ0Q29udmVyc2F0aW9uEAMSFgoSQ29udmVy",
            "c2F0aW9uU3RlcE9uEAQSDwoLUmVzcG9uc2VFbmQQBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ArmyAntMessage.System.ConversationStepType), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1), global::ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1.Parser, new[]{ "AppId", "ContentLength", "MessageCode", "ConversationCode", "ConversationStepIndex" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ConversationStepType {
    [pbr::OriginalName("Default")] Default = 0,
    [pbr::OriginalName("NoticeOnly")] NoticeOnly = 1,
    [pbr::OriginalName("AskFor")] AskFor = 2,
    [pbr::OriginalName("StartConversation")] StartConversation = 3,
    [pbr::OriginalName("ConversationStepOn")] ConversationStepOn = 4,
    /// <summary>
    /// Used to end an asking or conversation
    /// </summary>
    [pbr::OriginalName("ResponseEnd")] ResponseEnd = 5,
  }

  #endregion

  #region Messages
  public sealed partial class SocketExtendNormal_V0_0_0_1 : pb::IMessage<SocketExtendNormal_V0_0_0_1> {
    private static readonly pb::MessageParser<SocketExtendNormal_V0_0_0_1> _parser = new pb::MessageParser<SocketExtendNormal_V0_0_0_1>(() => new SocketExtendNormal_V0_0_0_1());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SocketExtendNormal_V0_0_0_1> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ArmyAntMessage.System.SocketHeadReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SocketExtendNormal_V0_0_0_1() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SocketExtendNormal_V0_0_0_1(SocketExtendNormal_V0_0_0_1 other) : this() {
      appId_ = other.appId_;
      contentLength_ = other.contentLength_;
      messageCode_ = other.messageCode_;
      conversationCode_ = other.conversationCode_;
      conversationStepIndex_ = other.conversationStepIndex_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SocketExtendNormal_V0_0_0_1 Clone() {
      return new SocketExtendNormal_V0_0_0_1(this);
    }

    /// <summary>Field number for the "app_id" field.</summary>
    public const int AppIdFieldNumber = 1;
    private long appId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long AppId {
      get { return appId_; }
      set {
        appId_ = value;
      }
    }

    /// <summary>Field number for the "content_length" field.</summary>
    public const int ContentLengthFieldNumber = 2;
    private int contentLength_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ContentLength {
      get { return contentLength_; }
      set {
        contentLength_ = value;
      }
    }

    /// <summary>Field number for the "message_code" field.</summary>
    public const int MessageCodeFieldNumber = 3;
    private int messageCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MessageCode {
      get { return messageCode_; }
      set {
        messageCode_ = value;
      }
    }

    /// <summary>Field number for the "conversation_code" field.</summary>
    public const int ConversationCodeFieldNumber = 4;
    private int conversationCode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ConversationCode {
      get { return conversationCode_; }
      set {
        conversationCode_ = value;
      }
    }

    /// <summary>Field number for the "conversation_step_index" field.</summary>
    public const int ConversationStepIndexFieldNumber = 5;
    private int conversationStepIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ConversationStepIndex {
      get { return conversationStepIndex_; }
      set {
        conversationStepIndex_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SocketExtendNormal_V0_0_0_1);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SocketExtendNormal_V0_0_0_1 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AppId != other.AppId) return false;
      if (ContentLength != other.ContentLength) return false;
      if (MessageCode != other.MessageCode) return false;
      if (ConversationCode != other.ConversationCode) return false;
      if (ConversationStepIndex != other.ConversationStepIndex) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AppId != 0L) hash ^= AppId.GetHashCode();
      if (ContentLength != 0) hash ^= ContentLength.GetHashCode();
      if (MessageCode != 0) hash ^= MessageCode.GetHashCode();
      if (ConversationCode != 0) hash ^= ConversationCode.GetHashCode();
      if (ConversationStepIndex != 0) hash ^= ConversationStepIndex.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AppId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(AppId);
      }
      if (ContentLength != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ContentLength);
      }
      if (MessageCode != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(MessageCode);
      }
      if (ConversationCode != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(ConversationCode);
      }
      if (ConversationStepIndex != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ConversationStepIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AppId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AppId);
      }
      if (ContentLength != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ContentLength);
      }
      if (MessageCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MessageCode);
      }
      if (ConversationCode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ConversationCode);
      }
      if (ConversationStepIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ConversationStepIndex);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SocketExtendNormal_V0_0_0_1 other) {
      if (other == null) {
        return;
      }
      if (other.AppId != 0L) {
        AppId = other.AppId;
      }
      if (other.ContentLength != 0) {
        ContentLength = other.ContentLength;
      }
      if (other.MessageCode != 0) {
        MessageCode = other.MessageCode;
      }
      if (other.ConversationCode != 0) {
        ConversationCode = other.ConversationCode;
      }
      if (other.ConversationStepIndex != 0) {
        ConversationStepIndex = other.ConversationStepIndex;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AppId = input.ReadInt64();
            break;
          }
          case 16: {
            ContentLength = input.ReadInt32();
            break;
          }
          case 24: {
            MessageCode = input.ReadInt32();
            break;
          }
          case 32: {
            ConversationCode = input.ReadInt32();
            break;
          }
          case 40: {
            ConversationStepIndex = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
