// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ArmyAntMessage/System/SessionStart.proto

#include "ArmyAntMessage/System/SessionStart.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace ArmyAntMessage {
namespace System {
class ClientEnterDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ClientEnter> _instance;
} _ClientEnter_default_instance_;
}  // namespace System
}  // namespace ArmyAntMessage
static void InitDefaultsClientEnter_ArmyAntMessage_2fSystem_2fSessionStart_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ArmyAntMessage::System::_ClientEnter_default_instance_;
    new (ptr) ::ArmyAntMessage::System::ClientEnter();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ArmyAntMessage::System::ClientEnter::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ClientEnter_ArmyAntMessage_2fSystem_2fSessionStart_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsClientEnter_ArmyAntMessage_2fSystem_2fSessionStart_2eproto}, {}};

void InitDefaults_ArmyAntMessage_2fSystem_2fSessionStart_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_ClientEnter_ArmyAntMessage_2fSystem_2fSessionStart_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_ArmyAntMessage_2fSystem_2fSessionStart_2eproto[1];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_ArmyAntMessage_2fSystem_2fSessionStart_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_ArmyAntMessage_2fSystem_2fSessionStart_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_ArmyAntMessage_2fSystem_2fSessionStart_2eproto::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ArmyAntMessage::System::ClientEnter, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ArmyAntMessage::System::ClientEnter)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::ArmyAntMessage::System::_ClientEnter_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_ArmyAntMessage_2fSystem_2fSessionStart_2eproto = {
  {}, AddDescriptors_ArmyAntMessage_2fSystem_2fSessionStart_2eproto, "ArmyAntMessage/System/SessionStart.proto", schemas,
  file_default_instances, TableStruct_ArmyAntMessage_2fSystem_2fSessionStart_2eproto::offsets,
  file_level_metadata_ArmyAntMessage_2fSystem_2fSessionStart_2eproto, 1, file_level_enum_descriptors_ArmyAntMessage_2fSystem_2fSessionStart_2eproto, file_level_service_descriptors_ArmyAntMessage_2fSystem_2fSessionStart_2eproto,
};

::google::protobuf::internal::DescriptorTable descriptor_table_ArmyAntMessage_2fSystem_2fSessionStart_2eproto = {
  false, InitDefaults_ArmyAntMessage_2fSystem_2fSessionStart_2eproto, 
  "\n(ArmyAntMessage/System/SessionStart.pro"
  "to\022\025ArmyAntMessage.System\"\r\n\013ClientEnter"
  "b\006proto3"
,
  "ArmyAntMessage/System/SessionStart.proto", &assign_descriptors_table_ArmyAntMessage_2fSystem_2fSessionStart_2eproto, 88,
};

void AddDescriptors_ArmyAntMessage_2fSystem_2fSessionStart_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_ArmyAntMessage_2fSystem_2fSessionStart_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_ArmyAntMessage_2fSystem_2fSessionStart_2eproto = []() { AddDescriptors_ArmyAntMessage_2fSystem_2fSessionStart_2eproto(); return true; }();
namespace ArmyAntMessage {
namespace System {

// ===================================================================

void ClientEnter::InitAsDefaultInstance() {
}
class ClientEnter::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClientEnter::ClientEnter()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ArmyAntMessage.System.ClientEnter)
}
ClientEnter::ClientEnter(const ClientEnter& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ArmyAntMessage.System.ClientEnter)
}

void ClientEnter::SharedCtor() {
}

ClientEnter::~ClientEnter() {
  // @@protoc_insertion_point(destructor:ArmyAntMessage.System.ClientEnter)
  SharedDtor();
}

void ClientEnter::SharedDtor() {
}

void ClientEnter::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ClientEnter& ClientEnter::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ClientEnter_ArmyAntMessage_2fSystem_2fSessionStart_2eproto.base);
  return *internal_default_instance();
}


void ClientEnter::Clear() {
// @@protoc_insertion_point(message_clear_start:ArmyAntMessage.System.ClientEnter)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ClientEnter::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ClientEnter*>(object);
  ::google::protobuf::uint32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ::google::protobuf::uint32 tag;
    ptr = Varint::Parse32Inline(ptr, &tag);
    if (!ptr) goto error;
    switch (tag >> 3) {
      case 0: goto error;
      default: {
      handle_unusual: (void)&&handle_unusual;
        if ((tag & 7) == 4) {
          if (!ctx->ValidEndGroup(tag)) goto error;
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
error:
  return nullptr;
len_delim_till_end: (void)&&len_delim_till_end;
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                                 {parser_till_end, object}, size);
group_continues: (void)&&group_continues;
  GOOGLE_DCHECK(ptr >= end);
  ctx->StoreGroup({_InternalParse, msg}, {parser_till_end, object}, depth);
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ClientEnter::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ArmyAntMessage.System.ClientEnter)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:ArmyAntMessage.System.ClientEnter)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ArmyAntMessage.System.ClientEnter)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ClientEnter::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ArmyAntMessage.System.ClientEnter)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ArmyAntMessage.System.ClientEnter)
}

::google::protobuf::uint8* ClientEnter::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ArmyAntMessage.System.ClientEnter)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ArmyAntMessage.System.ClientEnter)
  return target;
}

size_t ClientEnter::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ArmyAntMessage.System.ClientEnter)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ClientEnter::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ArmyAntMessage.System.ClientEnter)
  GOOGLE_DCHECK_NE(&from, this);
  const ClientEnter* source =
      ::google::protobuf::DynamicCastToGenerated<ClientEnter>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ArmyAntMessage.System.ClientEnter)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ArmyAntMessage.System.ClientEnter)
    MergeFrom(*source);
  }
}

void ClientEnter::MergeFrom(const ClientEnter& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ArmyAntMessage.System.ClientEnter)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void ClientEnter::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ArmyAntMessage.System.ClientEnter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClientEnter::CopyFrom(const ClientEnter& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ArmyAntMessage.System.ClientEnter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientEnter::IsInitialized() const {
  return true;
}

void ClientEnter::Swap(ClientEnter* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClientEnter::InternalSwap(ClientEnter* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ClientEnter::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_ArmyAntMessage_2fSystem_2fSessionStart_2eproto);
  return ::file_level_metadata_ArmyAntMessage_2fSystem_2fSessionStart_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace System
}  // namespace ArmyAntMessage
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ArmyAntMessage::System::ClientEnter* Arena::CreateMaybeMessage< ::ArmyAntMessage::System::ClientEnter >(Arena* arena) {
  return Arena::CreateInternal< ::ArmyAntMessage::System::ClientEnter >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
