// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ArmyAntMessage/System/SessionStart.proto

#ifndef PROTOBUF_INCLUDED_ArmyAntMessage_2fSystem_2fSessionStart_2eproto
#define PROTOBUF_INCLUDED_ArmyAntMessage_2fSystem_2fSessionStart_2eproto

#include <limits>
#include <string>

#include <google/protobuf/stubs/common.h>
#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ArmyAntMessage_2fSystem_2fSessionStart_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_ArmyAntMessage_2fSystem_2fSessionStart_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_ArmyAntMessage_2fSystem_2fSessionStart_2eproto();
namespace ArmyAntMessage {
namespace System {
class ClientEnter;
class ClientEnterDefaultTypeInternal;
extern ClientEnterDefaultTypeInternal _ClientEnter_default_instance_;
}  // namespace System
}  // namespace ArmyAntMessage
namespace google {
namespace protobuf {
template<> ::ArmyAntMessage::System::ClientEnter* Arena::CreateMaybeMessage<::ArmyAntMessage::System::ClientEnter>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace ArmyAntMessage {
namespace System {

// ===================================================================

class ClientEnter : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ArmyAntMessage.System.ClientEnter) */ {
 public:
  ClientEnter();
  virtual ~ClientEnter();

  ClientEnter(const ClientEnter& from);

  inline ClientEnter& operator=(const ClientEnter& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ClientEnter(ClientEnter&& from) noexcept
    : ClientEnter() {
    *this = ::std::move(from);
  }

  inline ClientEnter& operator=(ClientEnter&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ClientEnter& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ClientEnter* internal_default_instance() {
    return reinterpret_cast<const ClientEnter*>(
               &_ClientEnter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ClientEnter* other);
  friend void swap(ClientEnter& a, ClientEnter& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ClientEnter* New() const final {
    return CreateMaybeMessage<ClientEnter>(NULL);
  }

  ClientEnter* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ClientEnter>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ClientEnter& from);
  void MergeFrom(const ClientEnter& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientEnter* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:ArmyAntMessage.System.ClientEnter)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ArmyAntMessage_2fSystem_2fSessionStart_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ClientEnter

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace System
}  // namespace ArmyAntMessage

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_ArmyAntMessage_2fSystem_2fSessionStart_2eproto
