// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ArmyAntMessage/System/SocketHead.proto

#include "ArmyAntMessage/System/SocketHead.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace ArmyAntMessage {
namespace System {
class SocketExtendNormal_V0_0_0_1DefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SocketExtendNormal_V0_0_0_1>
      _instance;
} _SocketExtendNormal_V0_0_0_1_default_instance_;
}  // namespace System
}  // namespace ArmyAntMessage
namespace protobuf_ArmyAntMessage_2fSystem_2fSocketHead_2eproto {
void InitDefaultsSocketExtendNormal_V0_0_0_1Impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::ArmyAntMessage::System::_SocketExtendNormal_V0_0_0_1_default_instance_;
    new (ptr) ::ArmyAntMessage::System::SocketExtendNormal_V0_0_0_1();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ArmyAntMessage::System::SocketExtendNormal_V0_0_0_1::InitAsDefaultInstance();
}

void InitDefaultsSocketExtendNormal_V0_0_0_1() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsSocketExtendNormal_V0_0_0_1Impl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ArmyAntMessage::System::SocketExtendNormal_V0_0_0_1, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ArmyAntMessage::System::SocketExtendNormal_V0_0_0_1, app_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ArmyAntMessage::System::SocketExtendNormal_V0_0_0_1, content_length_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ArmyAntMessage::System::SocketExtendNormal_V0_0_0_1, message_code_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ArmyAntMessage::System::SocketExtendNormal_V0_0_0_1)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::ArmyAntMessage::System::_SocketExtendNormal_V0_0_0_1_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "ArmyAntMessage/System/SocketHead.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n&ArmyAntMessage/System/SocketHead.proto"
      "\022\025ArmyAntMessage.System\"[\n\033SocketExtendN"
      "ormal_V0_0_0_1\022\016\n\006app_id\030\001 \001(\003\022\026\n\016conten"
      "t_length\030\002 \001(\005\022\024\n\014message_code\030\003 \001(\005b\006pr"
      "oto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 164);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ArmyAntMessage/System/SocketHead.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_ArmyAntMessage_2fSystem_2fSocketHead_2eproto
namespace ArmyAntMessage {
namespace System {

// ===================================================================

void SocketExtendNormal_V0_0_0_1::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SocketExtendNormal_V0_0_0_1::kAppIdFieldNumber;
const int SocketExtendNormal_V0_0_0_1::kContentLengthFieldNumber;
const int SocketExtendNormal_V0_0_0_1::kMessageCodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SocketExtendNormal_V0_0_0_1::SocketExtendNormal_V0_0_0_1()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_ArmyAntMessage_2fSystem_2fSocketHead_2eproto::InitDefaultsSocketExtendNormal_V0_0_0_1();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1)
}
SocketExtendNormal_V0_0_0_1::SocketExtendNormal_V0_0_0_1(const SocketExtendNormal_V0_0_0_1& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&app_id_, &from.app_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&message_code_) -
    reinterpret_cast<char*>(&app_id_)) + sizeof(message_code_));
  // @@protoc_insertion_point(copy_constructor:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1)
}

void SocketExtendNormal_V0_0_0_1::SharedCtor() {
  ::memset(&app_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&message_code_) -
      reinterpret_cast<char*>(&app_id_)) + sizeof(message_code_));
  _cached_size_ = 0;
}

SocketExtendNormal_V0_0_0_1::~SocketExtendNormal_V0_0_0_1() {
  // @@protoc_insertion_point(destructor:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1)
  SharedDtor();
}

void SocketExtendNormal_V0_0_0_1::SharedDtor() {
}

void SocketExtendNormal_V0_0_0_1::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SocketExtendNormal_V0_0_0_1::descriptor() {
  ::protobuf_ArmyAntMessage_2fSystem_2fSocketHead_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ArmyAntMessage_2fSystem_2fSocketHead_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SocketExtendNormal_V0_0_0_1& SocketExtendNormal_V0_0_0_1::default_instance() {
  ::protobuf_ArmyAntMessage_2fSystem_2fSocketHead_2eproto::InitDefaultsSocketExtendNormal_V0_0_0_1();
  return *internal_default_instance();
}

SocketExtendNormal_V0_0_0_1* SocketExtendNormal_V0_0_0_1::New(::google::protobuf::Arena* arena) const {
  SocketExtendNormal_V0_0_0_1* n = new SocketExtendNormal_V0_0_0_1;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SocketExtendNormal_V0_0_0_1::Clear() {
// @@protoc_insertion_point(message_clear_start:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&app_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&message_code_) -
      reinterpret_cast<char*>(&app_id_)) + sizeof(message_code_));
  _internal_metadata_.Clear();
}

bool SocketExtendNormal_V0_0_0_1::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 app_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &app_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 content_length = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &content_length_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 message_code = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &message_code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1)
  return false;
#undef DO_
}

void SocketExtendNormal_V0_0_0_1::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 app_id = 1;
  if (this->app_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->app_id(), output);
  }

  // int32 content_length = 2;
  if (this->content_length() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->content_length(), output);
  }

  // int32 message_code = 3;
  if (this->message_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->message_code(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1)
}

::google::protobuf::uint8* SocketExtendNormal_V0_0_0_1::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 app_id = 1;
  if (this->app_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->app_id(), target);
  }

  // int32 content_length = 2;
  if (this->content_length() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->content_length(), target);
  }

  // int32 message_code = 3;
  if (this->message_code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->message_code(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1)
  return target;
}

size_t SocketExtendNormal_V0_0_0_1::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int64 app_id = 1;
  if (this->app_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->app_id());
  }

  // int32 content_length = 2;
  if (this->content_length() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->content_length());
  }

  // int32 message_code = 3;
  if (this->message_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->message_code());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SocketExtendNormal_V0_0_0_1::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1)
  GOOGLE_DCHECK_NE(&from, this);
  const SocketExtendNormal_V0_0_0_1* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SocketExtendNormal_V0_0_0_1>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1)
    MergeFrom(*source);
  }
}

void SocketExtendNormal_V0_0_0_1::MergeFrom(const SocketExtendNormal_V0_0_0_1& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.app_id() != 0) {
    set_app_id(from.app_id());
  }
  if (from.content_length() != 0) {
    set_content_length(from.content_length());
  }
  if (from.message_code() != 0) {
    set_message_code(from.message_code());
  }
}

void SocketExtendNormal_V0_0_0_1::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SocketExtendNormal_V0_0_0_1::CopyFrom(const SocketExtendNormal_V0_0_0_1& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SocketExtendNormal_V0_0_0_1::IsInitialized() const {
  return true;
}

void SocketExtendNormal_V0_0_0_1::Swap(SocketExtendNormal_V0_0_0_1* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SocketExtendNormal_V0_0_0_1::InternalSwap(SocketExtendNormal_V0_0_0_1* other) {
  using std::swap;
  swap(app_id_, other->app_id_);
  swap(content_length_, other->content_length_);
  swap(message_code_, other->message_code_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SocketExtendNormal_V0_0_0_1::GetMetadata() const {
  protobuf_ArmyAntMessage_2fSystem_2fSocketHead_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ArmyAntMessage_2fSystem_2fSocketHead_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace System
}  // namespace ArmyAntMessage

// @@protoc_insertion_point(global_scope)
