// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ArmyAntMessage/System/SocketHead.proto

#ifndef PROTOBUF_ArmyAntMessage_2fSystem_2fSocketHead_2eproto__INCLUDED
#define PROTOBUF_ArmyAntMessage_2fSystem_2fSocketHead_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_ArmyAntMessage_2fSystem_2fSocketHead_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsSocketExtendNormal_V0_0_0_1Impl();
void InitDefaultsSocketExtendNormal_V0_0_0_1();
inline void InitDefaults() {
  InitDefaultsSocketExtendNormal_V0_0_0_1();
}
}  // namespace protobuf_ArmyAntMessage_2fSystem_2fSocketHead_2eproto
namespace ArmyAntMessage {
namespace System {
class SocketExtendNormal_V0_0_0_1;
class SocketExtendNormal_V0_0_0_1DefaultTypeInternal;
extern SocketExtendNormal_V0_0_0_1DefaultTypeInternal _SocketExtendNormal_V0_0_0_1_default_instance_;
}  // namespace System
}  // namespace ArmyAntMessage
namespace ArmyAntMessage {
namespace System {

// ===================================================================

class SocketExtendNormal_V0_0_0_1 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1) */ {
 public:
  SocketExtendNormal_V0_0_0_1();
  virtual ~SocketExtendNormal_V0_0_0_1();

  SocketExtendNormal_V0_0_0_1(const SocketExtendNormal_V0_0_0_1& from);

  inline SocketExtendNormal_V0_0_0_1& operator=(const SocketExtendNormal_V0_0_0_1& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SocketExtendNormal_V0_0_0_1(SocketExtendNormal_V0_0_0_1&& from) noexcept
    : SocketExtendNormal_V0_0_0_1() {
    *this = ::std::move(from);
  }

  inline SocketExtendNormal_V0_0_0_1& operator=(SocketExtendNormal_V0_0_0_1&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SocketExtendNormal_V0_0_0_1& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SocketExtendNormal_V0_0_0_1* internal_default_instance() {
    return reinterpret_cast<const SocketExtendNormal_V0_0_0_1*>(
               &_SocketExtendNormal_V0_0_0_1_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(SocketExtendNormal_V0_0_0_1* other);
  friend void swap(SocketExtendNormal_V0_0_0_1& a, SocketExtendNormal_V0_0_0_1& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SocketExtendNormal_V0_0_0_1* New() const PROTOBUF_FINAL { return New(NULL); }

  SocketExtendNormal_V0_0_0_1* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SocketExtendNormal_V0_0_0_1& from);
  void MergeFrom(const SocketExtendNormal_V0_0_0_1& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SocketExtendNormal_V0_0_0_1* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 app_id = 1;
  void clear_app_id();
  static const int kAppIdFieldNumber = 1;
  ::google::protobuf::int64 app_id() const;
  void set_app_id(::google::protobuf::int64 value);

  // int32 content_length = 2;
  void clear_content_length();
  static const int kContentLengthFieldNumber = 2;
  ::google::protobuf::int32 content_length() const;
  void set_content_length(::google::protobuf::int32 value);

  // int32 message_code = 3;
  void clear_message_code();
  static const int kMessageCodeFieldNumber = 3;
  ::google::protobuf::int32 message_code() const;
  void set_message_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 app_id_;
  ::google::protobuf::int32 content_length_;
  ::google::protobuf::int32 message_code_;
  mutable int _cached_size_;
  friend struct ::protobuf_ArmyAntMessage_2fSystem_2fSocketHead_2eproto::TableStruct;
  friend void ::protobuf_ArmyAntMessage_2fSystem_2fSocketHead_2eproto::InitDefaultsSocketExtendNormal_V0_0_0_1Impl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SocketExtendNormal_V0_0_0_1

// int64 app_id = 1;
inline void SocketExtendNormal_V0_0_0_1::clear_app_id() {
  app_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 SocketExtendNormal_V0_0_0_1::app_id() const {
  // @@protoc_insertion_point(field_get:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1.app_id)
  return app_id_;
}
inline void SocketExtendNormal_V0_0_0_1::set_app_id(::google::protobuf::int64 value) {
  
  app_id_ = value;
  // @@protoc_insertion_point(field_set:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1.app_id)
}

// int32 content_length = 2;
inline void SocketExtendNormal_V0_0_0_1::clear_content_length() {
  content_length_ = 0;
}
inline ::google::protobuf::int32 SocketExtendNormal_V0_0_0_1::content_length() const {
  // @@protoc_insertion_point(field_get:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1.content_length)
  return content_length_;
}
inline void SocketExtendNormal_V0_0_0_1::set_content_length(::google::protobuf::int32 value) {
  
  content_length_ = value;
  // @@protoc_insertion_point(field_set:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1.content_length)
}

// int32 message_code = 3;
inline void SocketExtendNormal_V0_0_0_1::clear_message_code() {
  message_code_ = 0;
}
inline ::google::protobuf::int32 SocketExtendNormal_V0_0_0_1::message_code() const {
  // @@protoc_insertion_point(field_get:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1.message_code)
  return message_code_;
}
inline void SocketExtendNormal_V0_0_0_1::set_message_code(::google::protobuf::int32 value) {
  
  message_code_ = value;
  // @@protoc_insertion_point(field_set:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1.message_code)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace System
}  // namespace ArmyAntMessage

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ArmyAntMessage_2fSystem_2fSocketHead_2eproto__INCLUDED
