// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ArmyAntMessage/System/SocketHead.proto

#ifndef PROTOBUF_INCLUDED_ArmyAntMessage_2fSystem_2fSocketHead_2eproto
#define PROTOBUF_INCLUDED_ArmyAntMessage_2fSystem_2fSocketHead_2eproto

#include <limits>
#include <string>

#include <google/protobuf/stubs/common.h>
#if GOOGLE_PROTOBUF_VERSION < 3006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ArmyAntMessage_2fSystem_2fSocketHead_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_ArmyAntMessage_2fSystem_2fSocketHead_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_ArmyAntMessage_2fSystem_2fSocketHead_2eproto();
namespace ArmyAntMessage {
namespace System {
class SocketExtendNormal_V0_0_0_1;
class SocketExtendNormal_V0_0_0_1DefaultTypeInternal;
extern SocketExtendNormal_V0_0_0_1DefaultTypeInternal _SocketExtendNormal_V0_0_0_1_default_instance_;
}  // namespace System
}  // namespace ArmyAntMessage
namespace google {
namespace protobuf {
template<> ::ArmyAntMessage::System::SocketExtendNormal_V0_0_0_1* Arena::CreateMaybeMessage<::ArmyAntMessage::System::SocketExtendNormal_V0_0_0_1>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace ArmyAntMessage {
namespace System {

enum ConversationStepType {
  Default = 0,
  NoticeOnly = 1,
  AskFor = 2,
  StartConversation = 3,
  ConversationStepOn = 4,
  ResponseEnd = 5,
  ConversationStepType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::min(),
  ConversationStepType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::max()
};
bool ConversationStepType_IsValid(int value);
const ConversationStepType ConversationStepType_MIN = Default;
const ConversationStepType ConversationStepType_MAX = ResponseEnd;
const int ConversationStepType_ARRAYSIZE = ConversationStepType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ConversationStepType_descriptor();
inline const ::std::string& ConversationStepType_Name(ConversationStepType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ConversationStepType_descriptor(), value);
}
inline bool ConversationStepType_Parse(
    const ::std::string& name, ConversationStepType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ConversationStepType>(
    ConversationStepType_descriptor(), name, value);
}
// ===================================================================

class SocketExtendNormal_V0_0_0_1 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1) */ {
 public:
  SocketExtendNormal_V0_0_0_1();
  virtual ~SocketExtendNormal_V0_0_0_1();

  SocketExtendNormal_V0_0_0_1(const SocketExtendNormal_V0_0_0_1& from);

  inline SocketExtendNormal_V0_0_0_1& operator=(const SocketExtendNormal_V0_0_0_1& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SocketExtendNormal_V0_0_0_1(SocketExtendNormal_V0_0_0_1&& from) noexcept
    : SocketExtendNormal_V0_0_0_1() {
    *this = ::std::move(from);
  }

  inline SocketExtendNormal_V0_0_0_1& operator=(SocketExtendNormal_V0_0_0_1&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const SocketExtendNormal_V0_0_0_1& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SocketExtendNormal_V0_0_0_1* internal_default_instance() {
    return reinterpret_cast<const SocketExtendNormal_V0_0_0_1*>(
               &_SocketExtendNormal_V0_0_0_1_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(SocketExtendNormal_V0_0_0_1* other);
  friend void swap(SocketExtendNormal_V0_0_0_1& a, SocketExtendNormal_V0_0_0_1& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SocketExtendNormal_V0_0_0_1* New() const final {
    return CreateMaybeMessage<SocketExtendNormal_V0_0_0_1>(NULL);
  }

  SocketExtendNormal_V0_0_0_1* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SocketExtendNormal_V0_0_0_1>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SocketExtendNormal_V0_0_0_1& from);
  void MergeFrom(const SocketExtendNormal_V0_0_0_1& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SocketExtendNormal_V0_0_0_1* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 app_id = 1;
  void clear_app_id();
  static const int kAppIdFieldNumber = 1;
  ::google::protobuf::int64 app_id() const;
  void set_app_id(::google::protobuf::int64 value);

  // int32 content_length = 2;
  void clear_content_length();
  static const int kContentLengthFieldNumber = 2;
  ::google::protobuf::int32 content_length() const;
  void set_content_length(::google::protobuf::int32 value);

  // int32 message_code = 3;
  void clear_message_code();
  static const int kMessageCodeFieldNumber = 3;
  ::google::protobuf::int32 message_code() const;
  void set_message_code(::google::protobuf::int32 value);

  // int32 conversation_code = 4;
  void clear_conversation_code();
  static const int kConversationCodeFieldNumber = 4;
  ::google::protobuf::int32 conversation_code() const;
  void set_conversation_code(::google::protobuf::int32 value);

  // int32 conversation_step_index = 5;
  void clear_conversation_step_index();
  static const int kConversationStepIndexFieldNumber = 5;
  ::google::protobuf::int32 conversation_step_index() const;
  void set_conversation_step_index(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 app_id_;
  ::google::protobuf::int32 content_length_;
  ::google::protobuf::int32 message_code_;
  ::google::protobuf::int32 conversation_code_;
  ::google::protobuf::int32 conversation_step_index_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ArmyAntMessage_2fSystem_2fSocketHead_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SocketExtendNormal_V0_0_0_1

// int64 app_id = 1;
inline void SocketExtendNormal_V0_0_0_1::clear_app_id() {
  app_id_ = GOOGLE_PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 SocketExtendNormal_V0_0_0_1::app_id() const {
  // @@protoc_insertion_point(field_get:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1.app_id)
  return app_id_;
}
inline void SocketExtendNormal_V0_0_0_1::set_app_id(::google::protobuf::int64 value) {
  
  app_id_ = value;
  // @@protoc_insertion_point(field_set:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1.app_id)
}

// int32 content_length = 2;
inline void SocketExtendNormal_V0_0_0_1::clear_content_length() {
  content_length_ = 0;
}
inline ::google::protobuf::int32 SocketExtendNormal_V0_0_0_1::content_length() const {
  // @@protoc_insertion_point(field_get:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1.content_length)
  return content_length_;
}
inline void SocketExtendNormal_V0_0_0_1::set_content_length(::google::protobuf::int32 value) {
  
  content_length_ = value;
  // @@protoc_insertion_point(field_set:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1.content_length)
}

// int32 message_code = 3;
inline void SocketExtendNormal_V0_0_0_1::clear_message_code() {
  message_code_ = 0;
}
inline ::google::protobuf::int32 SocketExtendNormal_V0_0_0_1::message_code() const {
  // @@protoc_insertion_point(field_get:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1.message_code)
  return message_code_;
}
inline void SocketExtendNormal_V0_0_0_1::set_message_code(::google::protobuf::int32 value) {
  
  message_code_ = value;
  // @@protoc_insertion_point(field_set:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1.message_code)
}

// int32 conversation_code = 4;
inline void SocketExtendNormal_V0_0_0_1::clear_conversation_code() {
  conversation_code_ = 0;
}
inline ::google::protobuf::int32 SocketExtendNormal_V0_0_0_1::conversation_code() const {
  // @@protoc_insertion_point(field_get:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1.conversation_code)
  return conversation_code_;
}
inline void SocketExtendNormal_V0_0_0_1::set_conversation_code(::google::protobuf::int32 value) {
  
  conversation_code_ = value;
  // @@protoc_insertion_point(field_set:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1.conversation_code)
}

// int32 conversation_step_index = 5;
inline void SocketExtendNormal_V0_0_0_1::clear_conversation_step_index() {
  conversation_step_index_ = 0;
}
inline ::google::protobuf::int32 SocketExtendNormal_V0_0_0_1::conversation_step_index() const {
  // @@protoc_insertion_point(field_get:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1.conversation_step_index)
  return conversation_step_index_;
}
inline void SocketExtendNormal_V0_0_0_1::set_conversation_step_index(::google::protobuf::int32 value) {
  
  conversation_step_index_ = value;
  // @@protoc_insertion_point(field_set:ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1.conversation_step_index)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace System
}  // namespace ArmyAntMessage

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::ArmyAntMessage::System::ConversationStepType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ArmyAntMessage::System::ConversationStepType>() {
  return ::ArmyAntMessage::System::ConversationStepType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_ArmyAntMessage_2fSystem_2fSocketHead_2eproto
