// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ArmyAntServer.System.SocketHead.proto

#include "ArmyAntServer.System.SocketHead.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace ArmyAntServer {
namespace System {
class SocketExtendNormal_V0_0_0_1DefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SocketExtendNormal_V0_0_0_1>
      _instance;
} _SocketExtendNormal_V0_0_0_1_default_instance_;
}  // namespace System
}  // namespace ArmyAntServer
namespace protobuf_ArmyAntServer_2eSystem_2eSocketHead_2eproto {
void InitDefaultsSocketExtendNormal_V0_0_0_1Impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::ArmyAntServer::System::_SocketExtendNormal_V0_0_0_1_default_instance_;
    new (ptr) ::ArmyAntServer::System::SocketExtendNormal_V0_0_0_1();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ArmyAntServer::System::SocketExtendNormal_V0_0_0_1::InitAsDefaultInstance();
}

void InitDefaultsSocketExtendNormal_V0_0_0_1() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsSocketExtendNormal_V0_0_0_1Impl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ArmyAntServer::System::SocketExtendNormal_V0_0_0_1, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ArmyAntServer::System::SocketExtendNormal_V0_0_0_1, appid_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ArmyAntServer::System::SocketExtendNormal_V0_0_0_1)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::ArmyAntServer::System::_SocketExtendNormal_V0_0_0_1_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "ArmyAntServer.System.SocketHead.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n%ArmyAntServer.System.SocketHead.proto\022"
      "\024ArmyAntServer.System\",\n\033SocketExtendNor"
      "mal_V0_0_0_1\022\r\n\005appid\030\001 \001(\003b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 115);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ArmyAntServer.System.SocketHead.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_ArmyAntServer_2eSystem_2eSocketHead_2eproto
namespace ArmyAntServer {
namespace System {

// ===================================================================

void SocketExtendNormal_V0_0_0_1::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SocketExtendNormal_V0_0_0_1::kAppidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SocketExtendNormal_V0_0_0_1::SocketExtendNormal_V0_0_0_1()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_ArmyAntServer_2eSystem_2eSocketHead_2eproto::InitDefaultsSocketExtendNormal_V0_0_0_1();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:ArmyAntServer.System.SocketExtendNormal_V0_0_0_1)
}
SocketExtendNormal_V0_0_0_1::SocketExtendNormal_V0_0_0_1(const SocketExtendNormal_V0_0_0_1& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  appid_ = from.appid_;
  // @@protoc_insertion_point(copy_constructor:ArmyAntServer.System.SocketExtendNormal_V0_0_0_1)
}

void SocketExtendNormal_V0_0_0_1::SharedCtor() {
  appid_ = GOOGLE_LONGLONG(0);
  _cached_size_ = 0;
}

SocketExtendNormal_V0_0_0_1::~SocketExtendNormal_V0_0_0_1() {
  // @@protoc_insertion_point(destructor:ArmyAntServer.System.SocketExtendNormal_V0_0_0_1)
  SharedDtor();
}

void SocketExtendNormal_V0_0_0_1::SharedDtor() {
}

void SocketExtendNormal_V0_0_0_1::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SocketExtendNormal_V0_0_0_1::descriptor() {
  ::protobuf_ArmyAntServer_2eSystem_2eSocketHead_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ArmyAntServer_2eSystem_2eSocketHead_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SocketExtendNormal_V0_0_0_1& SocketExtendNormal_V0_0_0_1::default_instance() {
  ::protobuf_ArmyAntServer_2eSystem_2eSocketHead_2eproto::InitDefaultsSocketExtendNormal_V0_0_0_1();
  return *internal_default_instance();
}

SocketExtendNormal_V0_0_0_1* SocketExtendNormal_V0_0_0_1::New(::google::protobuf::Arena* arena) const {
  SocketExtendNormal_V0_0_0_1* n = new SocketExtendNormal_V0_0_0_1;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SocketExtendNormal_V0_0_0_1::Clear() {
// @@protoc_insertion_point(message_clear_start:ArmyAntServer.System.SocketExtendNormal_V0_0_0_1)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  appid_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool SocketExtendNormal_V0_0_0_1::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ArmyAntServer.System.SocketExtendNormal_V0_0_0_1)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 appid = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &appid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ArmyAntServer.System.SocketExtendNormal_V0_0_0_1)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ArmyAntServer.System.SocketExtendNormal_V0_0_0_1)
  return false;
#undef DO_
}

void SocketExtendNormal_V0_0_0_1::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ArmyAntServer.System.SocketExtendNormal_V0_0_0_1)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 appid = 1;
  if (this->appid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->appid(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ArmyAntServer.System.SocketExtendNormal_V0_0_0_1)
}

::google::protobuf::uint8* SocketExtendNormal_V0_0_0_1::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ArmyAntServer.System.SocketExtendNormal_V0_0_0_1)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 appid = 1;
  if (this->appid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->appid(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ArmyAntServer.System.SocketExtendNormal_V0_0_0_1)
  return target;
}

size_t SocketExtendNormal_V0_0_0_1::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ArmyAntServer.System.SocketExtendNormal_V0_0_0_1)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int64 appid = 1;
  if (this->appid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->appid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SocketExtendNormal_V0_0_0_1::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ArmyAntServer.System.SocketExtendNormal_V0_0_0_1)
  GOOGLE_DCHECK_NE(&from, this);
  const SocketExtendNormal_V0_0_0_1* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SocketExtendNormal_V0_0_0_1>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ArmyAntServer.System.SocketExtendNormal_V0_0_0_1)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ArmyAntServer.System.SocketExtendNormal_V0_0_0_1)
    MergeFrom(*source);
  }
}

void SocketExtendNormal_V0_0_0_1::MergeFrom(const SocketExtendNormal_V0_0_0_1& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ArmyAntServer.System.SocketExtendNormal_V0_0_0_1)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.appid() != 0) {
    set_appid(from.appid());
  }
}

void SocketExtendNormal_V0_0_0_1::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ArmyAntServer.System.SocketExtendNormal_V0_0_0_1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SocketExtendNormal_V0_0_0_1::CopyFrom(const SocketExtendNormal_V0_0_0_1& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ArmyAntServer.System.SocketExtendNormal_V0_0_0_1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SocketExtendNormal_V0_0_0_1::IsInitialized() const {
  return true;
}

void SocketExtendNormal_V0_0_0_1::Swap(SocketExtendNormal_V0_0_0_1* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SocketExtendNormal_V0_0_0_1::InternalSwap(SocketExtendNormal_V0_0_0_1* other) {
  using std::swap;
  swap(appid_, other->appid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SocketExtendNormal_V0_0_0_1::GetMetadata() const {
  protobuf_ArmyAntServer_2eSystem_2eSocketHead_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ArmyAntServer_2eSystem_2eSocketHead_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace System
}  // namespace ArmyAntServer

// @@protoc_insertion_point(global_scope)
