# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ArmyAntMessage/System/SessionStart.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ArmyAntMessage.System.ClientEnter" do
  end
end

module ArmyAntMessage
  module System
    ClientEnter = Google::Protobuf::DescriptorPool.generated_pool.lookup("ArmyAntMessage.System.ClientEnter").msgclass
  end
end
