# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ArmyAntMessage/System/SocketHead.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1" do
    optional :app_id, :int64, 1
    optional :content_length, :int32, 2
    optional :message_code, :int32, 3
    optional :conversation_code, :int32, 4
    optional :conversation_step_index, :int32, 5
  end
  add_enum "ArmyAntMessage.System.ConversationStepType" do
    value :Default, 0
    value :NoticeOnly, 1
    value :AskFor, 2
    value :StartConversation, 3
    value :ConversationStepOn, 4
    value :ResponseEnd, 5
  end
end

module ArmyAntMessage
  module System
    SocketExtendNormal_V0_0_0_1 = Google::Protobuf::DescriptorPool.generated_pool.lookup("ArmyAntMessage.System.SocketExtendNormal_V0_0_0_1").msgclass
    ConversationStepType = Google::Protobuf::DescriptorPool.generated_pool.lookup("ArmyAntMessage.System.ConversationStepType").enummodule
  end
end
