# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ArmyAntMessage/DBProxy/SqlRequest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ArmyAntMessage/DBProxy/SqlRequest.proto',
  package='ArmyAntMessage.DBProxy',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\'ArmyAntMessage/DBProxy/SqlRequest.proto\x12\x16\x41rmyAntMessage.DBProxy\"|\n\nSqlHeadOne\x12\x0e\n\x06length\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61talogName\x18\x02 \x01(\t\x12\x12\n\ncolumnName\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\x05\x12\x11\n\tallowNumm\x18\x05 \x01(\x08\x12\x14\n\x0c\x61utoIncrease\x18\x06 \x01(\x08\"\x18\n\x06SqlRow\x12\x0e\n\x06\x66ields\x18\x01 \x03(\t\"R\n\x0fSqlDatabaseInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06server\x18\x02 \x01(\t\x12\x0f\n\x07\x63harset\x18\x03 \x01(\t\x12\x10\n\x08sortRule\x18\x04 \x01(\t\"}\n\x0cSqlTableInfo\x12\x11\n\ttableName\x18\x05 \x01(\t\x12\x0e\n\x06\x65ngine\x18\x06 \x01(\t\x12\x0f\n\x07\x63omment\x18\x07 \x01(\t\x12\x39\n\x08\x64\x61tabase\x18\x08 \x01(\x0b\x32\'.ArmyAntMessage.DBProxy.SqlDatabaseInfo\"\xa1\x01\n\tSqlResult\x12\x33\n\x05table\x18\x01 \x01(\x0b\x32$.ArmyAntMessage.DBProxy.SqlTableInfo\x12\x31\n\x05heads\x18\x02 \x03(\x0b\x32\".ArmyAntMessage.DBProxy.SqlHeadOne\x12,\n\x04rows\x18\x03 \x03(\x0b\x32\x1e.ArmyAntMessage.DBProxy.SqlRow\"5\n\x12\x41ny2Dbp_SqlRequest\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x11\n\ttableName\x18\x02 \x01(\tb\x06proto3')
)




_SQLHEADONE = _descriptor.Descriptor(
  name='SqlHeadOne',
  full_name='ArmyAntMessage.DBProxy.SqlHeadOne',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='ArmyAntMessage.DBProxy.SqlHeadOne.length', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='catalogName', full_name='ArmyAntMessage.DBProxy.SqlHeadOne.catalogName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='columnName', full_name='ArmyAntMessage.DBProxy.SqlHeadOne.columnName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='ArmyAntMessage.DBProxy.SqlHeadOne.type', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='allowNumm', full_name='ArmyAntMessage.DBProxy.SqlHeadOne.allowNumm', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='autoIncrease', full_name='ArmyAntMessage.DBProxy.SqlHeadOne.autoIncrease', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=191,
)


_SQLROW = _descriptor.Descriptor(
  name='SqlRow',
  full_name='ArmyAntMessage.DBProxy.SqlRow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fields', full_name='ArmyAntMessage.DBProxy.SqlRow.fields', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=217,
)


_SQLDATABASEINFO = _descriptor.Descriptor(
  name='SqlDatabaseInfo',
  full_name='ArmyAntMessage.DBProxy.SqlDatabaseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ArmyAntMessage.DBProxy.SqlDatabaseInfo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='server', full_name='ArmyAntMessage.DBProxy.SqlDatabaseInfo.server', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='charset', full_name='ArmyAntMessage.DBProxy.SqlDatabaseInfo.charset', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sortRule', full_name='ArmyAntMessage.DBProxy.SqlDatabaseInfo.sortRule', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=301,
)


_SQLTABLEINFO = _descriptor.Descriptor(
  name='SqlTableInfo',
  full_name='ArmyAntMessage.DBProxy.SqlTableInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tableName', full_name='ArmyAntMessage.DBProxy.SqlTableInfo.tableName', index=0,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='engine', full_name='ArmyAntMessage.DBProxy.SqlTableInfo.engine', index=1,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comment', full_name='ArmyAntMessage.DBProxy.SqlTableInfo.comment', index=2,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='database', full_name='ArmyAntMessage.DBProxy.SqlTableInfo.database', index=3,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=428,
)


_SQLRESULT = _descriptor.Descriptor(
  name='SqlResult',
  full_name='ArmyAntMessage.DBProxy.SqlResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table', full_name='ArmyAntMessage.DBProxy.SqlResult.table', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heads', full_name='ArmyAntMessage.DBProxy.SqlResult.heads', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rows', full_name='ArmyAntMessage.DBProxy.SqlResult.rows', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=592,
)


_ANY2DBP_SQLREQUEST = _descriptor.Descriptor(
  name='Any2Dbp_SqlRequest',
  full_name='ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tableName', full_name='ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest.tableName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=594,
  serialized_end=647,
)

_SQLTABLEINFO.fields_by_name['database'].message_type = _SQLDATABASEINFO
_SQLRESULT.fields_by_name['table'].message_type = _SQLTABLEINFO
_SQLRESULT.fields_by_name['heads'].message_type = _SQLHEADONE
_SQLRESULT.fields_by_name['rows'].message_type = _SQLROW
DESCRIPTOR.message_types_by_name['SqlHeadOne'] = _SQLHEADONE
DESCRIPTOR.message_types_by_name['SqlRow'] = _SQLROW
DESCRIPTOR.message_types_by_name['SqlDatabaseInfo'] = _SQLDATABASEINFO
DESCRIPTOR.message_types_by_name['SqlTableInfo'] = _SQLTABLEINFO
DESCRIPTOR.message_types_by_name['SqlResult'] = _SQLRESULT
DESCRIPTOR.message_types_by_name['Any2Dbp_SqlRequest'] = _ANY2DBP_SQLREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SqlHeadOne = _reflection.GeneratedProtocolMessageType('SqlHeadOne', (_message.Message,), dict(
  DESCRIPTOR = _SQLHEADONE,
  __module__ = 'ArmyAntMessage.DBProxy.SqlRequest_pb2'
  # @@protoc_insertion_point(class_scope:ArmyAntMessage.DBProxy.SqlHeadOne)
  ))
_sym_db.RegisterMessage(SqlHeadOne)

SqlRow = _reflection.GeneratedProtocolMessageType('SqlRow', (_message.Message,), dict(
  DESCRIPTOR = _SQLROW,
  __module__ = 'ArmyAntMessage.DBProxy.SqlRequest_pb2'
  # @@protoc_insertion_point(class_scope:ArmyAntMessage.DBProxy.SqlRow)
  ))
_sym_db.RegisterMessage(SqlRow)

SqlDatabaseInfo = _reflection.GeneratedProtocolMessageType('SqlDatabaseInfo', (_message.Message,), dict(
  DESCRIPTOR = _SQLDATABASEINFO,
  __module__ = 'ArmyAntMessage.DBProxy.SqlRequest_pb2'
  # @@protoc_insertion_point(class_scope:ArmyAntMessage.DBProxy.SqlDatabaseInfo)
  ))
_sym_db.RegisterMessage(SqlDatabaseInfo)

SqlTableInfo = _reflection.GeneratedProtocolMessageType('SqlTableInfo', (_message.Message,), dict(
  DESCRIPTOR = _SQLTABLEINFO,
  __module__ = 'ArmyAntMessage.DBProxy.SqlRequest_pb2'
  # @@protoc_insertion_point(class_scope:ArmyAntMessage.DBProxy.SqlTableInfo)
  ))
_sym_db.RegisterMessage(SqlTableInfo)

SqlResult = _reflection.GeneratedProtocolMessageType('SqlResult', (_message.Message,), dict(
  DESCRIPTOR = _SQLRESULT,
  __module__ = 'ArmyAntMessage.DBProxy.SqlRequest_pb2'
  # @@protoc_insertion_point(class_scope:ArmyAntMessage.DBProxy.SqlResult)
  ))
_sym_db.RegisterMessage(SqlResult)

Any2Dbp_SqlRequest = _reflection.GeneratedProtocolMessageType('Any2Dbp_SqlRequest', (_message.Message,), dict(
  DESCRIPTOR = _ANY2DBP_SQLREQUEST,
  __module__ = 'ArmyAntMessage.DBProxy.SqlRequest_pb2'
  # @@protoc_insertion_point(class_scope:ArmyAntMessage.DBProxy.Any2Dbp_SqlRequest)
  ))
_sym_db.RegisterMessage(Any2Dbp_SqlRequest)


# @@protoc_insertion_point(module_scope)
